# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-state-123456789012"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "dev/terraform.tfstate"
    region         = "us-east-1"
  }
}
