# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-1"

  default_tags {
    tags = { "ManagedBy" : "Terragrunt", "Repository" : "infrastructure", "Team" : "platform", "Terraform" : "true" }
  }
}
